### ISSUE TITLE
speed up timeexpansion

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/unfold.jl#10]
The current implementation of `designmatrix.jl/time_expand` is very slow (i.e. 1000Hz with 1000 events takes ~150s to run) . This takes ~1-2s in Matlab. The reason is different implementation, in Julia we allow for events inbetween sampling rates, i.e. for each event we generate a new designmatrix and then add/concatenate them. This is well possible for fMRI with slow sampling rates & not that many events. But for EEG this is limiting.

The bottleneck (with 99% time spend) is:

```julia
                      tmp = A[fromRowIx:toRowIx,fromColIx:toColIx-1]+Gc
                        A[fromRowIx:toRowIx,fromColIx:toColIx-1] = tmp # this line is superslow!

```

Which includes the newly generated basisfunction into a larger matrix.

I tried to manually sum up all basis function and generate multiple sparse matrices and concatenating them, instead of indexing in a large one. But the creating alone of a sparse matrix of that size took superlong, so I don't think I will spend more time on this.

The matrix is large (3.000.000 x 1.000 or so), but very sparse, i.e. 0.00025% of elements are non-zero.

**Comment by behinger** [comment]
so I could add a specification to basisfunction "exact", which would allow user to come back to the exact implementation if needed, and else use a faster convolution type approach.

**Comment by behinger** [comment]
ok added the exact = false method ("exact" is a new property of basisfunction). The designmatrix is generated by convolution. But, turns out, convolution of two sparse matrices is not implemented => it is somewhat slow again, sometimes even slower than exact (overhead convolution?)

still way too slow.

Btw. I can't make use of the matlab implementation which simply shifts/lags the predictor, because the basis-function returns me a kernel. I could make an exception for firbasis but that just dodges the issue for the most common kernel.

**Comment by kleinschmidt** [comment]
It really shouldn't take so long to create such a matrix... I wonder if it's creating a lot of new temporary arrays and that's what's making it slow?  Have you tried doing it in place?  like 

```julia
A[fromRowIx:toRowIx,fromColIx:toColIx-1] .+= Gc 
```

or is there something else happening in between those two lines that means you can't do this?

**Comment by behinger** [comment]
Removed exact again, lineraized everything in a smarter way than the first time round. now it is fast enough :-)
