### ISSUE TITLE
Outdated information in "Traditional Mass Univariate Analysis" tutorial

### ISSUE THREAD

**Issue by jschepers** [unfoldtoolbox/Unfold.jl#139]
Some of the information in the "Traditional Mass Univariate Analysis" tutorial is outdated. 

For example:
https://github.com/unfoldtoolbox/Unfold.jl/blob/ec496457ae15847a3fc056891a3b4147aa681c90/docs/src/tutorials/lm_mu.md?plain=1#L92C1-L92C1

**Comment by behinger** [comment]
fixed in main :)
