### ISSUE TITLE
Confusing usage of acronyms

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/Unfold.jl#181]
I met an acronym FIR basisfunction in https://unfoldtoolbox.github.io/Unfold.jl/dev/explanations/basisfunctions/ and in https://unfoldtoolbox.github.io/Unfold.jl/dev/tutorials/lm_overlap/#3.-fit-the-linear-model

However I couldn't find any explanation what does it means and how to decipher it. Would be nice to have one.

**Comment by behinger** [comment]
fixed, thanks!
FIR stands for [Finite-Impulse-Response](https://en.wikipedia.org/wiki/Finite_impulse_response) and is a term taken from the filtering-literature.
