### ISSUE TITLE
formatting of coefnames

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/Unfold.jl#185]
![image](https://github.com/unfoldtoolbox/Unfold.jl/assets/33777074/1096cfc0-b22f-46d7-8342-d46c04cb09ca)

I think the formatting of this function should be changed:
- excessive spaces - deleted
- it will throw an error if name is not specified #183 
- long numbers - rounded

**Comment by behinger** [comment]
the  number formatting is unfotunate, I will see what I can do. But it would be a breaking change.

the excessive space I want to keep also for `extract_coef_info` to split things in its parts

**Comment by vladdez** [comment]
Unfortunately it looks badly when used as labels.

**Comment by behinger** [comment]
yes, the idea of hierrachical labels in my mind would be anyway to split them up using ´extract_coef_info` and put them hierarchical, not all timepoints need to be labelled with the basisfunction, e.g.an label to the label

**Comment by behinger** [comment]
wontfix

**Comment by vladdez** [comment]
> wontfix

Pardon?

**Comment by behinger** [comment]
ah sorry, that is a github-tag-name, I won't fix this
