### ISSUE TITLE
output of designmatrix() is not very user-friendly

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/Unfold.jl#193]
![image](https://github.com/unfoldtoolbox/Unfold.jl/assets/33777074/e4b1a18f-43d9-4444-9c1b-4b838e3cb254)

1. Would be nice to make better formatting
2. What are Xs here? How about to rename it to something more meaningful?

**Comment by behinger** [comment]
![grafik](https://github.com/unfoldtoolbox/Unfold.jl/assets/10183650/2cacf3a7-8f1c-48d6-98ce-51f1205827d5)
will be fixed in #192

**Comment by vladdez** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/10183650/321948811-2cacf3a7-8f1c-48d6-98ce-51f1205827d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDgyMDQsIm5iZiI6MTcxMzM0NzkwNCwicGF0aCI6Ii8xMDE4MzY1MC8zMjE5NDg4MTEtMmNhY2YzYTctOGYxYy00OGQ2LTk4Y2UtNTFmMTIwNTgyN2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA5NTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNGUyNGM4YWMzZDkzZDhmZjI3NjZkNDQyZmQ5MTRiY2M3YzViNjFmM2Y2M2Q3MTJjZGVhZmI0ZjE2YmZiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NB-23I3LOSs0boWEwGrGbQP8uAsOxmy5J1axZOlLH6I) will be fixed in #192

- Seem like "sizes" and "useful functions" should start with capital letters
- Idea with colors is great!
