### ISSUE TITLE
FileIO.load does not work

### ISSUE THREAD

**Issue by ReneSkukies** [unfoldtoolbox/Unfold.jl#194]
I attempted to load some previously saved UnfoldModels and ran into an error. Debugging a bit it relates to the following three lines in the load function (lines 53-55 in load.jl)

```julia
    f = jldopen(file, "r")
    uf = f["uf"]
    close(f)
```

Just running the function I get the following error:
```julia-repl
[ Info: Attempting to dynamically load CodecZlib
ERROR: ArgumentError: Package CodecZlib not found in current path.
- Run `import Pkg; Pkg.add("CodecZlib")` to install the CodecZlib package.
```
Adding CodecZlip does not resolve the issue.

When running the three lines manually on with the same file it seems that ```jldopen``` works fine, however, indexing into the file using ```f["uf"]``` throws the above error.
Even more curiously, running ```f["uf"]``` a second time without having closed the file seems to work as intended. (closing the file and running the two lines again results in the same error)

At this point I think this might be a compat issues, since there have been bugs like these before with the JDL2.jl package. Did you recently update the packages with the new Unfold version?

**Comment by behinger** [comment]
should be fixed in Unfold 0.6.10
