### ISSUE TITLE
documentation open issues

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/Unfold.jl#195]
- [x] solver_default => provide docstring
- [x] predict_partial_overlap => make explanation for documentation
- [x] extend_to_larger => provide docstring

**Comment by ReneSkukies** [comment]
Currently, there is no documentation/ HowTo for ```predict()``` apart from the docstring:
- [ ] ```predict()``` => make HowTo for each/ multiple cases; link with ```predict_partial_overlap()``` explanation

**Comment by behinger** [comment]
I think I wanted to write something and never did... I'll put it on my list
