### ISSUE TITLE
Inconsistency in predict( ) input; better docstring

### ISSUE THREAD

**Issue by ReneSkukies** [unfoldtoolbox/Unfold.jl#216]
Currently, there is an inconsistency in the input of the ```predict()``` function when using the ```keep_basis``` and ```exclude_basis``` keywords:

 ```julia
# Example 1; this one works
predict(
    m,
    Unfold.formulas(m),
    Unfold.events(m);
    overlap = true,
    keep_basis = ["basis_one"]
)

# Example 2; this one also works
predict(
    m,
    Unfold.formulas(m),
    Unfold.events(m);
    overlap = true,
    exclude_basis = "basis_two"
)

# Example 3; this one does not work
predict(
    m,
    Unfold.formulas(m),
    Unfold.events(m);
    overlap = true,
    keep_basis = "basis_one"
)
```

I think this should either be consistent or made apparent to the user.

The error results from the ```matrix_by_basisname(::AbstractMatrix, ::Any, !Matched::Vector)``` only accepting a vector as input. 

I think the easiest solution would be to force the user to use a vector from the start and provide useful error messages. The other option would be to convert to a vector. Either way this should also be made apparent in the docstring of ```predict()```

**Comment by ReneSkukies** [comment]
@behinger if you let me know what you prefer, I can make a pull request 👍🏼

**Comment by behinger** [comment]
ah thanks for catching. Indeed, I think I like the convenience function to wrap a single string input into a predictor like in `exclude_basis`

**Comment by ReneSkukies** [comment]
Working on it on the update_predict branch 👍🏼
