### ISSUE TITLE
Loosen tuple definition in utilities.epoch

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/unfold.jl#31]
In order to facilitate usage of functions via JuliaCall from R, we could loosen the \tau = Tuple{Numeric,Numeric} condition to ??

**Comment by palday** [comment]
Can you give an example of what's going wrong here / what the desired behavior is?

**Comment by behinger** [comment]
yes, still using issues as a note to myself ...[utilities.epoch](https://github.com/unfoldtoolbox/unfold.jl/blob/4a59c55c9f2e6a6bc9cb89aa01eefdc492520a37/src/utilities.jl#L6)
```julia
function epoch(data::Array{T,2},tbl::DataFrame,τ::Tuple{Number,Number},sfreq;eventtime::Symbol=:latency) where T <:Union{Missing,Number}
```
Here we enforce a tuple, but in R's JuliaCall it is not straightforward to define tuples (because they dont exist in R afaik). Thus I want to allow lists here too.

**Comment by palday** [comment]
So in that case I would just add another method that has tau as an array which then immediately dispatches to this variant:

```julia
epoch(data::Matrix tbl::DataFrame, τ::Vector,sfreq; eventtime::String="latency") = epoch(data, tbl, Tuple(τ...), sfreq; eventtime=Symbol(eventtime))
```
(not that I also converted Symbol to String for that indirection as well)

**Comment by behinger** [comment]
I like it! Makes lot of sense and I will implement it later, thanks
