### ISSUE TITLE
typo in fit.jl test

### ISSUE THREAD

**Issue by ssaket** [unfoldtoolbox/Unfold.jl#38]
Shouldn't `Dict index 1` have `(f2, b2)` as entry at L71?

https://github.com/unfoldtoolbox/Unfold.jl/blob/8724dd6e4224fc2fc979b6cd6371b594a4fa078a/test/fit.jl#L63-L71

**Comment by behinger** [comment]
yes indeed, good catch! Gonna fix it in a sec
