### ISSUE TITLE
LoadError: `Lines not defined` while using plot.jl

### ISSUE THREAD

**Issue by ssaket** [unfoldtoolbox/Unfold.jl#39]
I stumbled across this issue few times. It appears that in the plot.jl the use of `Lines` requires importing `CairoMakie` along with `AlgebraOfGraphics` otherwise it throws the error `LoadError: UndefVarError: Lines not defined`. 

I also looked in the [official tutorial]( http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/gallery/#Lines-and-markers) for AoG package and looks like, we import both; `using AlgebraOfGraphics, CairoMakie`

**Comment by behinger** [comment]
(minor: Plots.jl and Makie.jl are different packages)

I think there have been recently some updates in the structure of Makie.jl 

I think the correct way is to do
using AlgebraOfGraphics, CairoMakie # this one is for vectors/PDFs
or
using AlgebraOfGraphics, GLMakie  # This one is interactive 
or
using AlgebraOfGraphics, Makie # this one afaik has GLMakie as default
or
using AlgebraOfGraphics, AbstractPlotting  # maybe this one was deprecated, I dont remember the announcement.

I changed the line in plots.jl to include Makie. Hope that works!

**Comment by ssaket** [comment]
Yes, indeed. Makie works as well!
