### ISSUE TITLE
Documentation: Explanation/ HowTo on Effects both lead to 404 page

### ISSUE THREAD

**Issue by ReneSkukies** [unfoldtoolbox/Unfold.jl#91]
I also can't find the files in ./docs. Do they not exist yet or are they missing somehow?

**Comment by behinger** [comment]
sorry - I missed this one.

There is a longstanding issue with Literate.jl #86 - I havent fixed it yet, you can find this docu here:
https://github.com/unfoldtoolbox/Unfold.jl/tree/main/docs/src/_literate/HowTo

**Comment by behinger** [comment]
fixed finally - turns out, the `_literate` in the folder path makes Github ignore the directory completly... that one was hard to fin
